### ISSUE TITLE
Using `std::hash::hash` by mistake.

### ISSUE THREAD

**Issue by bluss** [seiflotfy/rust-cuckoofilter#16]
There's a line `use std::hash::{Hasher, Hash, hash};` in util.rs that imports the `hash` function. This is unstable but wasn't flagged due to bug rust-lang/rust/issues/28075.

It's unused, so fix is simply to remove the import.

**Comment by florianjacob** [comment]
@seiflotfy can be closed as this was fixed in the meantime.
