### ISSUE TITLE
Fingerprint is broken

### ISSUE THREAD

**Issue by burdges** [seiflotfy/rust-cuckoofilter#19]
It appears your fingerprint is being drawn from the indexing hash, meaning all elements inserted into a particular bucket will have the same hash.  It increases your false positive rate by 2^8, making this crate into an vanilla bloom filter with 1 hash function, butat that consumes 8 times the necessary space.  I'll try to send a pull request.

**Comment by koivunej** [comment]
Of all the open bugs in this repo this seems to be the most serious. I wonder if anyone has done any progress, or would like to open up more how this could be fixed?

**Comment by burdges** [comment]
I'll rewrite this from scratch eventually since I'll eventually need a Cuckoo filter and a Cuckoo table.  I started doing it last year, but got distracted by needless abstraction, like providing support for three or four bucket modes.  I've more pressing matters right now though.

**Comment by florianjacob** [comment]
If I understood this correctly: The 64bit hash value is truncated to 32bit at https://github.com/seiflotfy/rust-cuckoofilter/blob/master/src/util.rs#L16 . Those 32bits of the hash value are used as fingerprint at https://github.com/seiflotfy/rust-cuckoofilter/blob/master/src/util.rs#L36 *as well as as bucket index* at https://github.com/seiflotfy/rust-cuckoofilter/blob/master/src/util.rs#L46 , which is the source of the problem.

The reference implementation solves this at https://github.com/efficient/cuckoofilter/blob/master/src/cuckoofilter.h#L68 by splitting the 64bit hash value in half and using one part for the indexing, one part for the fingerprinting.

Also, I think it would be much better to read if there wasn't a conversion from and to byte arrays. I'll see whether I can find the time to fix that function properly.

**Comment by seiflotfy** [comment]
yeah this needs fixing! my bad
