### ISSUE TITLE
Allow fingerprint and bucket size to vary

### ISSUE THREAD

**Issue by seiflotfy** [seiflotfy/rust-cuckoofilter#3]
Right now a static size of 1 byte per fingerprint is being used. Fingerprint should be changed from u8 to Vec<u8>.

**Comment by LukasKalbertodt** [comment]
I think I disagree. Vec is a heap allocated buffer which introduces indirection which is bad for modern memory systems. As far as I understand the paper, the optimal bucket size is really small (like 2, 4 or 8), as is the fingerprint size (certainly below 16 bits). Using a Vec for a fingerprint (which is already 24 bytes on a 64 bit machine) is just crazy. 

I will submit a PR soon to change the bucket to a stack allocated array.

**Comment by seiflotfy** [comment]
OK then lets stick for now with a fingerprint of 1 byte and a bucket size of 4
Will close thing accordingly. We can change it in the future to adapt based on initial capacity

**Comment by AnthonyMikh** [comment]
@seiflotfy Actually, we can have a stack-allocated array with user-specified length using [generic-array](https://crates.io/crates/generic-array). Have you considered that option?
