### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by ravloony** [seiflotfy/rust-cuckoofilter#30]
Could you publish the 0.4.0 version to crates.io please?

Thank you!

**Comment by seiflotfy** [comment]
on it

**Comment by florianjacob** [comment]
Everything is done now, just the `cargo publish` is missing. I can't do that, because I'm only listed as *author* on https://crates.io/crates/cuckoofilter, not as *owner*. @seiflotfy can you do the publish and / or invite me as crate owner on crates.io?

**Comment by seiflotfy** [comment]
On It

**Comment by Libbum** [comment]
Hey @seiflotfy. Looks like the 0.4.0 still hasn't hit crates.io yet though. Is there a blocker happening I can help with?

**Comment by juliangehring** [comment]
Just to check, are there any blockers for releasing v0.4.0 on crates?

**Comment by mre** [comment]
Ping @seiflotfy. 😃
