### ISSUE TITLE
Arbitrary capacities?

### ISSUE THREAD

**Issue by robertsdotpm** [seiflotfy/rust-cuckoofilter#31]
I was playing around with the capacity sizes for the bloom filter and noticed that everything is rounded to powers of 2 (next_power_of_two()) Is this code really needed? It seems to blow up the filter size quite a lot.

**Comment by florianjacob** [comment]
That is indeed required for the base principle of cuckoo filters to work: Any two fingerprints XORed must result in a valid location.

You can tune the required space though by varying other parameters, like the number of bits used per fingerprint, or by using variants of Cuckoofilters that support dynamic growth.

**Comment by florianjacob** [comment]
See #5 for resizing.
